### ISSUE TITLE
NPR includes MN twice, MT not at all

### ISSUE THREAD

**Issue by mgold** [kristw/gridmap-layout-usa#1]
There is an error in `input/tiles_npr.csv` where `MN` appears twice. The left one should be `MT`.

I'm having trouble running `npm run compile` without error (node 5.5.0, npm 3.5.3) so I'll let you make the change. I did manage to get the new statistics and they are as follows:

```
npr,recall,0.8301886792452831
npr,primaryrecall,0.5849056603773585
npr,secondaryrecall,0.24528301886792453
npr,inaccuracy,0.17123287671232876
npr,misdirection,0.11363636363636363
```

The conclusions in the [Medium article](https://medium.com/@kristw/whose-grid-map-is-better-quality-metrics-for-grid-map-layouts-e3d6075d9e80#.80kzc4crd) are therefore incorrect. NPR does not have the lowest recall; that's The Guardian. It does not have the highest inaccuracy; that's Bloomberg.

Perhaps "has exactly 50 states" would make a good quality metric? `d3.set(states).values().length` would work, although you'd need to account for DC.

**Comment by kristw** [comment]
Thanks @mgold . I have corrected the data and updated the article.

**Comment by kristw** [comment]
I defined these metrics independent from the number of states, because I wanted all metrics to be relative to the intention of each layout. If the creator did not want to include DC, then the metrics should reflect if they did a good job with 50 regions, not 51. That's why _recall_ is normalized by the number of real geographic neighbor pairs. For bloomberg and 538, pairs that have DC are not counted as the denominator. 

Also, these metrics should be generalizable to any grid map, not just the US.

**Comment by mgold** [comment]
Thanks for taking care of this! Regarding the 50 state metric, it was more of an idea to detect other errors. I see you found one more with ZA/AZ, so it seems you double-checked everything. :+1:
